export const FR = {
  app: {
    name: "What Did I Promise?",
    tagline: "Ne laisse plus une promesse oubliée abîmer ta crédibilité.",
  },
  onboarding: {
    slide1: {
      title: "Tes promesses, quelque part de sûr",
      subtitle: "Tout ce que tu as dit que tu allais faire, en un seul endroit. Plus jamais de trou de mémoire embarrassant.",
      cta: "Continuer",
    },
    slide2: {
      title: "Ta parole a de la valeur",
      subtitle: "Suivre tes engagements, c'est protéger ta réputation, tes relations, et ta tranquillité d'esprit.",
      cta: "Continuer",
    },
    slide3: {
      title: "Prêt en moins de 10 secondes",
      subtitle: "Capture une promesse en quelques gestes. Sans friction. Toujours avec toi.",
      cta: "Commencer",
    },
  },
  home: {
    title: "Mes promesses",
    cta: "J'ai promis quelque chose",
    today: "Aujourd'hui",
    overdue: "En retard",
    thisWeek: "Cette semaine",
    atRisk: "À risque",
    reliability: "Fiabilité",
    lastCheckin: "Dernier check-in",
    noCheckinYet: "Pas encore de check-in",
    doCheckin: "Faire le check-in",
  },
  promises: {
    title: "Mes promesses",
    empty: "Aucune promesse ici.\nCommence par en enregistrer une.",
    emptyFiltered: "Aucune promesse ne correspond à tes filtres.",
    sections: {
      today: "Aujourd'hui",
      overdue: "En retard",
      thisWeek: "Cette semaine",
      noDate: "Sans date",
      recentlyDone: "Récemment tenues",
      all: "Toutes",
    },
  },
  capture: {
    title: "Nouvelle promesse",
    titleLabel: "Qu'as-tu promis ?",
    titlePlaceholder: "Ex : Envoyer le rapport avant vendredi...",
    personLabel: "À qui ?",
    personPlaceholder: "Sélectionner une personne (optionnel)",
    dueDateLabel: "Pour quand ?",
    priorityLabel: "Priorité",
    contextLabel: "Contexte",
    reminderLabel: "Rappel",
    tagLabel: "Tags",
    attachmentLabel: "Pièce jointe",
    cta: "Enregistrer ma promesse",
    success: "Promesse enregistrée.",
    errorEmpty: "Le titre de la promesse ne peut pas être vide.",
  },
  detail: {
    title: "Détail",
    actions: {
      markDone: "Marquer comme tenue",
      markInProgress: "En cours",
      snooze: "Reporter",
      cancel: "Annuler",
      addNote: "Ajouter une note",
      addReminder: "Ajouter un rappel",
      duplicate: "Dupliquer",
      archive: "Archiver",
      share: "Partager",
    },
    notes: "Notes de suivi",
    reminders: "Rappels",
    events: "Activité",
    noNotes: "Aucune note pour l'instant.",
    addNotePlaceholder: "Ajoute une note de suivi...",
  },
  people: {
    title: "Personnes",
    empty: "Aucune personne enregistrée.",
    addPerson: "Ajouter une personne",
    namePlaceholder: "Nom",
    typeLabel: "Type de relation",
    weightLabel: "Importance relationnelle",
    promises: "promesses",
  },
  templates: {
    title: "Templates",
    empty: "Aucun template disponible.",
    use: "Utiliser",
    builtIn: "Intégrés",
    custom: "Personnalisés",
  },
  checkin: {
    title: "Check-in du jour",
    subtitle: "Voici où tu en es aujourd'hui",
    today: "À faire aujourd'hui",
    overdue: "En retard",
    comingSoon: "Dans les prochains jours",
    atRisk: "À surveiller",
    notReviewed: "Pas revus récemment",
    allGood: "Tout est à jour. Bien joué !",
    done: "Check-in terminé",
  },
  stats: {
    title: "Fiabilité",
    score: "Score",
    kept: "Tenues",
    overdue: "En retard",
    snoozed: "Reportées",
    avgClosure: "Délai moyen",
    days: "jours",
    levels: {
      stable: "Stable",
      solide: "Solide",
      aRenforcer: "À renforcer",
      sousTension: "Sous tension",
    },
  },
  settings: {
    title: "Réglages",
    biometric: "Verrouillage biométrique",
    biometricDesc: "Protège l'app avec Face ID ou Touch ID",
    notifications: "Notifications",
    notificationsDesc: "Activer les rappels",
    premium: "Passer en Premium",
    premiumDesc: "Promesses illimitées, rappels multiples et plus",
    export: "Exporter mes données",
    about: "À propos",
    version: "Version",
  },
  paywall: {
    title: "Passe à Premium",
    subtitle: "Pour ceux qui tiennent vraiment leurs promesses",
    features: [
      "Promesses illimitées",
      "Personnes illimitées",
      "Rappels multiples",
      "Vue à risque avancée",
      "Historique complet",
      "Templates personnalisés",
      "Export local",
      "Filtres avancés",
      "Score de fiabilité détaillé",
      "Promesses récurrentes",
      "Tags personnalisés",
    ],
    cta: "Essayer gratuitement 7 jours",
    restore: "Restaurer mes achats",
    later: "Plus tard",
  },
  statuses: {
    ouverte: "Ouverte",
    en_cours: "En cours",
    tenue: "Tenue",
    reportee: "Reportée",
    annulee: "Annulée",
    en_retard: "En retard",
    archivee: "Archivée",
  },
  priorities: {
    faible: "Faible",
    normale: "Normale",
    elevee: "Élevée",
    critique: "Critique",
  },
  contexts: {
    personnel: "Personnel",
    travail: "Travail",
    famille: "Famille",
    amities: "Amitiés",
    administratif: "Administratif",
    sante: "Santé",
    finances: "Finances",
    maison: "Maison",
    autre: "Autre",
  },
  personTypes: {
    moi_meme: "Moi-même",
    ami: "Ami·e",
    famille: "Famille",
    collegue: "Collègue",
    client: "Client·e",
    partenaire: "Partenaire",
    autre: "Autre",
  },
  riskLevels: {
    faible: "Faible risque",
    attention: "Attention",
    surveiller: "À surveiller",
    critique: "Critique",
  },
  duePrecisions: {
    aucune: "Sans date",
    aujourd_hui: "Aujourd'hui",
    demain: "Demain",
    cette_semaine: "Cette semaine",
    ce_mois: "Ce mois",
    date_exacte: "Date exacte",
  },
  recurrences: {
    aucune: "Aucune",
    quotidienne: "Quotidienne",
    hebdomadaire: "Hebdomadaire",
    bimensuelle: "Bimensuelle",
    mensuelle: "Mensuelle",
    trimestrielle: "Trimestrielle",
    personnalisee: "Personnalisée",
  },
  feedback: {
    kept: [
      "Promesse tenue. Ta parole a de la valeur.",
      "Encore une promesse honorée. C'est ça, la fiabilité.",
      "Tu t'es engagé, tu as tenu. Ça compte.",
      "Une de plus dans la colonne des tenues. Bien joué.",
      "Ta réputation se construit ainsi, engagement après engagement.",
    ],
    staleReminder: "Tu avais promis ça il y a {days} jours. Toujours d'actualité ?",
    checkinReminder: "Ton check-in quotidien t'attend. 2 minutes pour rester à jour.",
    overdueAlert: "Attention : {count} promesse(s) en retard.",
  },
  errors: {
    generic: "Une erreur s'est produite. Réessaie.",
    dbInit: "Impossible d'initialiser la base de données.",
    notificationPermission: "Les notifications sont désactivées. Active-les dans les réglages.",
    biometricNotAvailable: "La biométrie n'est pas disponible sur cet appareil.",
  },
  confirm: {
    archive: "Archiver cette promesse ? Tu pourras la retrouver dans l'historique.",
    cancel_promise: "Annuler cette promesse ? Elle sera marquée comme annulée.",
    delete: "Supprimer définitivement ? Cette action est irréversible.",
    yes: "Oui",
    no: "Non",
    confirm: "Confirmer",
    back: "Retour",
  },
  share: {
    message: "Je t'ai promis : \"{title}\"\n\nC'est noté chez moi. — What Did I Promise?",
    title: "Partager ma promesse",
  },
  tabs: {
    home: "Accueil",
    promises: "Promesses",
    people: "Personnes",
    stats: "Fiabilité",
    settings: "Réglages",
  },
  filters: {
    all: "Toutes",
    status: "Statut",
    person: "Personne",
    context: "Contexte",
    priority: "Priorité",
    atRisk: "À risque",
    tags: "Tags",
    reset: "Réinitialiser",
  },
  nav: {
    back: "Retour",
    close: "Fermer",
    save: "Enregistrer",
    edit: "Modifier",
    add: "Ajouter",
  },
  risk: {
    title: "Promesses à risque",
    empty: "Aucune promesse à risque pour le moment.",
    subtitle: "Ces promesses méritent ton attention",
  },
};
